config/routes.rb
Rails.application.routes.draw do

  root  'static_pages#home'
  get   '/resume', to: 'static_pages#resume', as: 'resume'

  resources :projects
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :admin

  has_attached_file :image, default_url: "missing.jpg",
                    path: ':rails_root/public/system/:class/:attachment/:filename',
                    url: '/system/:class/:attachment/:filename',
                    styles: {portfolio: "640x480!"}

  validates_attachment :image,
    content_type: { content_type: /\Aimage\/.*\z/ },
    size: { in: 0..1.megabytes }

  def stripped_name
    name.gsub(/[ -]/, '_').downcase
  end

  def full_source
    return full_url(self.source_link)
  end

  def full_completed
    return full_url(self.complete_link)
  end

  private
    def full_url(link)
      link.start_with?('http://') || link.start_with?('https://') ? link : "http://#{link}"
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Redirect to root, instead of sign-in, if not authenticated
  def authenticate_admin!
    if admin_signed_in?
      super
    else
      redirect_to root_path, :notice => "That action is not allowed."
    end
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_admin!, except: [:index]
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    if admin_signed_in?
      @projects = Project.all
    else
      @projects = Project.where(active: true)
    end
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    @project.admin_id = current_admin.id

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_url, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_url, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description, :source_link, :complete_link, :active, :image)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def resume
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Kevin Rocker"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

  def nav_title(page_title = '')
    page_title.empty? ? "Home" : page_title
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-inverse navbar-footer footer">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li> Built in Ruby on Rails 5.0.0 <br>
      &copy; 2016 - Kevin Rocker</li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Logout", destroy_admin_session, method: :delete, data: { confirm: 'Are you sure?' } if admin_signed_in? %></li>
      <li><%= link_to "Source", "https://github.com/krocker34/portfolio-page-v01" %></li>
      <li><%= mail_to "kevin.j.rocker@gmail.com", "Email" %></li>
    </ul>
  </div>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class='container-fluid'>
    <ul class="nav navbar-nav">
      <!-- <li><%= link_to nav_title(yield(:title)), root_path %></li> -->
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home",       root_path %></li>
      <li><%= link_to "Portfolio",  projects_path %></li>
    </ul>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= full_title(yield(:title)) %> </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% if content_for? :before_flash %>
      <%= yield :before_flash %>
    <% end %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control', rows: "5" %>
  </div>

  <div class="field">
    <%= f.label :source_link %>
    <%= f.text_field :source_link, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :complete_link %>
    <%= f.text_field :complete_link, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active, class: 'form-control' %>
  </div>

  <div class="actions text-center">
    <%= f.submit msg %> <%= link_to 'Back', back_btn, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/projects/_project_buttons.html.erb
<%= link_to 'Edit', edit_project_path(project) %>
<%= link_to 'Delete', project_path(project), method: :delete, data: { confirm: 'Are you sure?' } %>
<% if project.active %>
  &#x2714
<% else %>
  &#x2718
<% end %>

app/views/projects/_title_links.html.erb
<h3>
  <% if project.complete_link.blank? %>
    project.name
  <% else %>
    <%= link_to project.name, project.full_completed %>
  <% end %>

  <small>
    <% if !(project.source_link.blank?) %>
      <%= link_to "(Source)", project.full_source %>
    <% end %>
  </small>
</h3> <br>

app/views/projects/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <h1>Update Project</h1>

    <div class="project_form">

      <%= render partial: 'form', locals: { project: @project,
                                            msg: "Submit Project",
                                            back_btn: project_path(@project.id) } %>

    </div>

  </div>
</div>

app/views/projects/index.html.erb
<% provide(:title, 'Portfolio') %>

<% content_for :before_flash do %>
<div class="container">
  <div class="row">
      <div class="col-lg-12">
          <h1 class="page-header">Projects and Pages
              <small> All the code that's fit to print </small>
              <% if admin_signed_in? %>
              <%= link_to 'New Project', new_project_path, class: 'btn btn-default'%>
              <% end %>
          </h1>

      </div>
  </div>
</div>
<% end %>

<% @projects.each_slice(3) do |slice| -%>
  <div class="row">
    <% slice.each do |p| -%>
      <div class="col-md-4 portfolio-item">
        <%= image_tag p.image.url(:portfolio), class: 'img-responsive' %>
        <%= render partial: 'title_links', locals: {project: p} %>
        <p> <%= truncate p.description, separator: " ", length: 255 %> </p>
        <%= render partial: 'project_buttons', locals: {project: p} if admin_signed_in? %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/projects/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <h1>New Project</h1>

    <div class="project_form">

      <%= render partial: 'form', locals: { project: @project,
                                            msg: "Submit Project",
                                            back_btn: projects_path } %>

    </div>

  </div>
</div>

app/views/projects/show.html.erb
<% if admin_signed_in? %>
  <%= link_to 'Edit', edit_project_path(@project), class: 'btn btn-primary' %>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Source link:</strong>
  <%= @project.source_link %>
</p>

<p>
  <strong>Complete link:</strong>
  <%= @project.complete_link %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @project.image, class: "img-thumbnail" %>
</p>

<p>
  <strong>Active:</strong>
  <%= @project.active %>
</p>

 |
<%= link_to 'Back', projects_path, class: 'btn btn-primary' %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<% content_for :before_flash do %>
  <header class="business-header">
      <div class="container">
          <div class="row">
              <div class="col-lg-12">
                  <h1 class="tagline">Kevin Rocker's HQ</h1>
              </div>
          </div>
      </div>
  </header>
<% end %>

<div class="row">
  <div class="col-sm-8">
      <h2>Who Am I?</h2>
      <p>
        I am an enthusastic junior web developer in Ruby on Rails and ReactJS. I have been coding in some capacity for as long as I can remember, and have been working this past year on developing a professional skillset for proper collaborative programming.
      </p>
      <p>
        Communication is extremely important to me. Whether it's communicating with a controller in Ruby, swapping AJAX calls to-and-fro, or explaining the latest esoteric code problem (or awesome new feature!) to a non-technical client, I'm always able to get my message across.
      </p>
      <p>
        <%= link_to "View My Portfolio", projects_path, class: "btn btn-default btn-lg" %>
      </p>
  </div>
  <div class="col-sm-4">
      <h2>Contact Me</h2>
      <address>
          <strong>Physical Presence</strong>
          <br>Charlotte, NC 28210
          <br>
      </address>
      <address>
          <strong>Online Presence</strong>
          <br> <%= link_to "LinkedIn", "http://www.linkedin.com/in/kevin-rocker" %>
          <br> <%= link_to "GitHub", "https://github.com/krocker34" %>
          <br> <%= mail_to "kevin.j.rocker@gmail.com", "Email" %>
          <br>
      </address>
  </div>
</div>

<div class="row">
  <div class="col-sm-4">
      <!-- <img class="img-circle img-responsive img-center" src="http://placehold.it/300x300" alt=""> -->
      <h2>Innovative</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
  <div class="col-sm-4">
      <!-- <img class="img-circle img-responsive img-center" src="http://placehold.it/300x300" alt=""> -->
      <h2>Passionate</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
  <div class="col-sm-4">
      <!-- <img class="img-circle img-responsive img-center" src="http://placehold.it/300x300" alt=""> -->
      <h2>Skilled</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<!-- /.row -->

app/views/static_pages/resume.html.erb
<% provide(:title, 'Resume') %>

<h1>StaticPages#resume</h1>
<p>Find me in app/views/static_pages/resume.html.erb</p>